insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'DDO', 'Direct Delivery Only', '1DM', 5.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'DDO', 'Direct Delivery Only', '2DM', 4.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'DDO', 'Direct Delivery Only', '3DM', 3.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'DDO', 'Direct Delivery Only', '4DM', 2.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'DDO', 'Direct Delivery Only', '5DM', 1.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RPS', 'Rural Pickup Surcharge', '1DM', 7.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RPS', 'Rural Pickup Surcharge', '2DM', 6.5000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RPS', 'Rural Pickup Surcharge', '3DM', 5.5000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RPS', 'Rural Pickup Surcharge', '4DM', 3.5000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RPS', 'Rural Pickup Surcharge', '5DM', 3.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RES', 'Residential Surcharge', '1DM', 5.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RES', 'Residential Surcharge', '2DM', 4.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RES', 'Residential Surcharge', '3DM', 3.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RES', 'Residential Surcharge', '4DM', 2.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'RES', 'Residential Surcharge', '5DM', 1.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'SLP', 'Peak Surcharge', '1DM', 5.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'SLP', 'Peak Surcharge', '2DM', 4.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'SLP', 'Peak Surcharge', '3DM', 3.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'SLP', 'Peak Surcharge', '4DM', 2.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'SLP', 'Peak Surcharge', '5DM', 1.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'FSC', 'Fuel Surcharge', '1DM', 5.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'FSC', 'Fuel Surcharge', '2DM', 4.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'FSC', 'Fuel Surcharge', '3DM', 3.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'FSC', 'Fuel Surcharge', '4DM', 2.0000);
insert into accessorial(acc_code,acc_name,service,flat_rate) values( 'FSC', 'Fuel Surcharge', '5DM', 1.0000);