insert into state(state_id, state_name, start_postal, end_postal,country_id) values('AK', 'Alaska', 99500, 99999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('AL', 'Alabama', 35000, 36999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('AR', 'Arkansas', 71600, 72999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('AZ', 'Arizone', 85000, 86599,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('CA', 'California', 90000, 96199,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('CO', 'Colorado', 80000, 81699,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('CT', 'Connecticut', 06000, 06999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('DC', 'District of Colombia', 20000, 20599,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('DE', 'Delaware', 19700, 19999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('FL', 'Florida', 32000, 34999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('GA', 'Georgia', 30000, 31999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('HI', 'Hawaii', 96700, 96899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('IA', 'Iowa', 50000, 52899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('ID', 'Idaho', 83200, 83899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('IL', 'Illinois', 60000, 62999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('IN', 'Indiana', 46000, 47999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('KS', 'Kansas', 66000, 67999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('KY', 'Kentucky', 40000, 42799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('LA', 'Losisiana', 70000, 71499,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MA', 'Massachusetts', 01000, 02799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MD', 'Maryland', 20600, 21999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('ME', 'Maine', 03900, 04999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MI', 'Michigan', 48000, 49999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MN', 'Minessota', 55000, 56799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MO', 'Missouri', 63000, 65899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MS', 'Mississippi', 38600, 39799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('MT', 'Montana', 59000, 59999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NC', 'North Carolina', 27000, 28999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('ND', 'North Dakota', 58000, 58999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NE', 'Nebraska', 68000, 69399,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NH', 'New Hampshire', 03000, 03899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NJ', 'New Jersey', 07000, 08999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NM', 'New Mexico', 87000, 88499,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NV', 'Nevada', 88900, 89899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('NY', 'New York', 04000, 06399,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('OH', 'Ohio', 43000, 45999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('OK', 'Oklahoma', 73000, 74999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('OR', 'Oregon', 97000, 97999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('PA', 'Pennsylvania', 15000, 19699,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('RI', 'Rhode Island', 02800, 02999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('SC', 'South Carolina', 29000, 29999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('SD', 'South Dakota', 57000, 57799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('TN', 'Tennessee', 37000, 38599,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('TX', 'Texas', 73000, 73399,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('UT', 'Utah', 84000, 84799,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('VA', 'Virginia', 22000, 24699,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('VT', 'Vermount', 05000, 05999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('WA', 'Washigton', 98800, 99499,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('WI', 'Wisconsin', 53000, 54999,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('WV', 'West Virginia', 24700, 26899,21);
insert into state(state_id, state_name, start_postal, end_postal,country_id) values('WY', 'Wyoming', 82000, 83422,21);
